version: "3.7"

services:
  db:
    image: mongo:4.4.1
    container_name: lilbot-mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 6000:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234